# Generated by Django 5.1 on 2024-09-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oubus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth',
            field=models.DateField(auto_now=True),
        ),
    ]
